### ISSUE TITLE
[Bug]: The app says it violates meta policies and when trying to open the app, it doesn't open.

### ISSUE THREAD

**Issue by ConnertheG** [LemonLoader/MelonLoader_057#12]
### All of the following criteria must be met

- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the game.
- [X] Tried reinstalling LemonLoader.
- [X] Tried restarting device.

### Describe the issue.

The app says it violates meta policies and when trying to open the app, it doesn't open.

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `/storage/emulated/0/Android/data/<package name>/files/melonloader/etc/Latest.log`

**Comment by TrevTV** [comment]
This is the only report of this I've seen and I can't replicate it myself, feel free to reopen if needed.
